####################################################
#               Lava Rising Config!                #
#               spaghetti code hell                #
#             Typical flow of phases:              #
#         Pre-Game > Grace > Main > Post           #
#   Overtime (might be skipped)  ^                 #
####################################################

game:
  # Config about general game settings.
  pregame:
    worldName: world
    # The name for the world being generated. This should be the same as level-name in your server.properties file.
    seed:
    # The seed for the world being generated. Leave blank to randomly generate a seed. This should only contain numbers.
    borderSize: 10
    # The size for the border at the start. Unit is the number of blocks for the border diameter.
    rerolling:
    # Rerolling is a feature that allows players to vote on "rerolling" a map, restarting the server so that a new world is generated.
    # Rerolling is disabled when the server starts, and will be enabled after X seconds.
    # This is to allow the world to load first, and to not cause any weird world gen bugs.
      enabled: true
      # Allow rerolling of the map by a command.
      rerollTimer: 15
      # How long to wait before rerolling is enabled. Unit is seconds.
      percentageToPass: 80
      # How many players need to agree on a reroll to reroll the map.
      rerollingEnabled: "Rerolling of the world is now enabled! Do /reroll to vote to reroll. %required% players needs to vote to reroll."
      # Action bar message to show when rerolling is enabled.
      # Replace %required% with the amount of votes required to reroll the map.
      kickMessage: "%sender% wants to reroll the map! Map is now being rerolled. Join back soon!"
      # The plugin kicks everyone when a reroll is decided upon to recreate a world. This will be the kick message.
      # Replace %sender% with the final person's decision to reroll the map.
  start:
    countdown: true
    # If this is enabled, the plugin will countdown X seconds before starting, or immediately start if this is false.
    timer: 5
    # How long to wait if "countdown" is true.
  grace:
    duration: 60
    # How long will the grace period last. Unit is seconds.
    finalBorderSize: 176
    # How big the border will expand to at the end. Unit is the number of blocks for the border diameter.
    # Keep in mind the amount of blocks needed to be filled by the plugin! 200 will start lagging the server, but it may not be depending on your hardware.
    speed: 30
    # How long should it take for the border to expand to its final size. Unit is seconds.

  main:
    indicatorTitle: The game is in the main period! Lava is at %level%, you are %distance% blocks away.
    # Instead of a timer, there will be an "indicator" meant for showing the lava level and how far away you are.
    # Replace %distance% with the distance a player is from the lava y-level.
    # Replace %level% with the lava y-level.
    # (Tip: Include %level% if overtime is enabled to warn players of impending overtime.)
    lavaInterval: 5
    # How fast the lava rises. Unit is seconds.
    deathMessage: "%original% and is eliminated! %left% players remaining."
    # What the death message should be.
    # Replace the original death message with %original%.
    # Replace the player who died with %player%.
    # Replace the amount of players left with %left%.
    quitMessage: "%original% and is eliminated! %left% players remaining."
    # What the disconnect message should be.
    # Replace the original death message with %original%.
    # Replace the player who died with %player%.
    # Replace the amount of players left with %left%.

  overtime:
    # Lava does not rise during overtime. Game ends when there is one person left alive!
    warning:
    # Warn the players about overtime? The warning will be shown by a chat message.
      enabled: true
      # self-explanatory
      message: Overtime triggers at Y %threshold%!
      # What the message will be.
      # Replace %threshold% with the threshold to activate overtime. Set below VVV
    threshold: 240
    # The level of lava needed for the game to be considered to be in overtime.
    # Keep in mind that the build limit is 320 on 1.18, and 255 on <1.18!
    finalBorderSize: 20
    # How small the border will shrink to. Unit is the number of blocks for the border diameter.
    speed: 120
    # How fast the border will shrink.
    # Make sure the speed is not too fast so that people can see it coming!
    title: OVERTIME! Lava is paused. Border will shrink slowly to the middle. Last one alive wins!
    # What to show on the action bar when its overtime.

  post:
    duration: 30
    # How long the server will wait before restarting the server.
    creativeMode: all
    # (mostly for fun) Who the game will give creative mode to at the end of the game.
    # Accepted values: 'none', 'winner', 'all'
    kickMessage: The game is restarting now. Join back soon!
    # What should be the kick message when the server is restarting.

# For all configs with the name 'timername', there is multiple variables that you can add. The game will automatically translate these variables.
timers:
  # The game frequently uses timers to display information to players. You can customize the look of the timers here!
  # Timers are sent using action bars, in the general format: "[||||||||||] / Message"

  # For all configs with "name", they specify the message the timer will show. You can add placeholders to the message.
  # Special placeholders for specific configs will be shown in the respective config.
  # Use %time_left% for the amount of seconds left in the timer.
  # Use %time_elapsed% for the amount of seconds elapsed.
  # Chat formatting also works, use ยง for the formatting.

  # For all config with "style", they specify the style of the timer, specifically the colour, size and formatting.
  # Look at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
  # style.border refers to the borders of the timer, which are the two brackets ([ and ])
  # style.empty refers to the empty notches in the timer. (|)
  # style.filled refers to the filled notches in the timer. (|)
  # style.delimiter refers to the delimiter between the timer and the message. (/)
  # style.size refers to the amount of notches in the timer.
  pregame:
    rerolling:
      name: "Rerolling of the map will be enabled in %time_left% seconds."
      style:
        border:
          - DARK_GREEN
          - BOLD
        empty:
          - GRAY
        filled:
          - GREEN
        delimiter:
          - DARK_GRAY
        size: 10
  start:
    name: "Starting in %time_left% seconds!"
    style:
      border:
        - DARK_GREEN
        - BOLD
      empty:
        - GRAY
      filled:
        - GREEN
      delimiter:
        - DARK_GRAY
      size: 5
  grace:
    name: "The game is in the grace period! PVP is off. %time_left% seconds left."
    style:
      border:
        - GOLD
        - BOLD
      empty:
        - GRAY
      filled:
        - YELLOW
      delimiter:
        - DARK_GRAY
      size: 20
  post:
    name: "%winner% has survived! The server will restart in %time_left% seconds."
    # Replace %winner% with the winner of the game.
    style:
      border:
        - DARK_BLUE
        - BOLD
      empty:
        - GRAY
      filled:
        - BLUE
      delimiter:
        - DARK_GRAY
      size: 10

debug:
  ignoreConfig:
    # The plugin will automatically edit some values in your files, specifically server.properties and bukkit.yml, to disable spawn protection, nether and end. This is for game balance and performance.
    # However, you can choose to ignore these checks. I would highly recommend leaving it as is, but it's your decision at the end.
    disableSpawnProtection: false
    # Spawn protection prevents non-op users from breaking or placing blocks near spawn.
    disableNether: false
    # Self-explanatory, this is disabled to prevent cheaters from hiding out from the lava in the nether.
    disableEnd: false
    # Self-explanatory, this is disabled to stop unnecessary saving of the end, and by extension speeds up the server restarting.
    allowFlight: false
    # Minecraft's built-in anticheat usually kicks more innocent players than cheaters, and you cannot rejoin during the main phase. Turning this off usually prevent false-positives from the anti-cheat, and improves player experience.
    # if you really want an anticheat install one from spigot
  restartSetup:
  # Attempt to automatically setup server restarting.
    enabled: false
    os: Unix
    # What operating system the server is running on. Leave blank to let the plugin detect automatically.
    # Accepted values: Windows, Mac, Unix, Solaris
    jar: spigot-1.17.1.jar
    # The name of the server jar. Leave blank to let the plugin detect automatically, although this is prone to fail.
    # Include .jar at the end!
